export type Lang = 'en' | 'ko';

export const ui = {
  en: {
    // Navbar
    'nav.research': 'Research',
    'nav.publications': 'Publications',
    'nav.people': 'People',
    'nav.news': 'News',
    'nav.history': 'History',
    'nav.radar': 'Radar',
    'nav.ideas': 'Ideas',
    'nav.join': 'Join us',
    'nav.langToggle': '한국어',

    // Footer
    'footer.navigate': 'Navigate',
    'footer.notes': 'Lab notes',
    'footer.contact': 'Contact',
    'footer.ideaLab': 'AI Idea Lab',
    'footer.researchRadar': 'Research Radar',
    'footer.affiliations':
      'Department of Psychology · Interdisciplinary Program in AI (IPAI) · Department of Brain & Cognitive Sciences',
    'footer.address': 'Office M512, Building 16<br />Seoul National University<br />1 Gwanak-ro, Gwanak-gu, Seoul',
    'footer.backToTop': 'Back to top',

    // Home
    'home.eyebrow': 'Seoul National University · Connectome Laboratory',
    'home.projectGeneratedSummary': 'AI-generated summary',
    'ideas.generatedSummary': 'Generated by',
    'ideas.generatedImage': 'Image generated by',
    'home.mottoCredit': 'Leonardo da Vinci',
    'home.missionLead': 'Understanding people',
    'home.missionFocus': 'through connections.',
    'home.metaDesc': 'Led by Jiook Cha at SNU, we study connections among genes, brain, behavior, and environment to understand human cognition, emotion, and mental health.',
    'home.heroDesc':
      'Why do people think, feel, and change differently? At the SNU Connectome Lab, led by Jiook Cha, we seek answers in the relationships among genes, brain, behavior, and environment. We study theories that could explain these relationships and predictive models that could apply to new people.',
    'home.inquiryEyebrow': 'Our approach',
    'home.inquiryTitle': 'What it means to study connections',
    'home.connectionDesc': 'A connectome maps connections within the brain. Our questions extend to how brain activity relates to a person’s experiences and circumstances. In developmental research, for example, we examine genetic variation and brain measurements alongside behavior, family relationships, school experience, and neighborhood conditions. This helps us ask what each observation reveals when read in relation to the others.',
    'home.approachTitle': 'Bringing explanation and prediction together',
    'home.approachDesc': 'We work with theoretical models that explain phenomena and AI models that learn predictive patterns from data. Our aim is to narrow the distance between predicting well and understanding why. Developing new tools goes together with examining the assumptions they carry.',
    'home.questionsTitle': 'Questions we pursue',
    'home.figureEyebrow': 'From our research',
    'home.figureLink': 'How we study brain signals',
    'home.piCta': 'Jiook Cha’s approach to research',
    'home.exploreCta': 'Our research questions',
    'home.peopleCta': 'People',
    'home.mapEyebrow': 'Research map',
    'home.mapTitle': 'Research areas and connections',
    'home.mapDesc':
      'This illustration introduces our research areas and possible connections. It does not show anatomical measurements. Select an area to read more.',
    'home.newsEyebrow': 'News',
    'home.newsTitle': 'Latest news',
    'home.allNews': 'All news',
    'home.researchEyebrow': 'Research',
    'home.researchTitle': 'Research areas',
    'home.researchDesc':
      'We study cognition, emotion, development, and mental health through connections among genes, brain, behavior, and environment, and develop models to investigate those relationships.',
    'home.readMore': 'Read more',
    'home.pubsEyebrow': 'Publications',
    'home.pubsTitle': 'Featured publications',
    'home.allPubs': 'All publications',
    'home.alumniEyebrow': 'Alumni',
    'home.alumniTitle': 'Alumni',
    'home.alumniCta': 'Current members and alumni',
    'home.joinTitle': 'Join the lab',
    'home.joinDesc':
      'Application information for graduate study, postdoctoral work, and undergraduate internships. Contact the lab about current openings.',
    'home.joinCta': 'How to apply',
    'home.emailPi': 'Email the lab',
    'home.projectsEyebrow': 'Open source',
    'home.projectsTitle': 'Code and projects',
    'home.projectsDesc': 'Recently updated lab repositories.',
    'home.allProjects': 'All code on GitHub',
    'home.projectPaper': 'Paper',
    'home.projectUpdated': 'Updated',

    // Research page
    'research.eyebrow': 'Research',
    'research.title': 'Research areas',
    'research.desc':
      'How can observations at different levels help us understand a person? We examine connections among genes, brain, behavior, and environment through four lines of inquiry. Each addresses a different part of the problem, from models of brain activity to development, emotional experience, and new computational methods.',
    'research.approach':
      'The map introduces each question and approach. The studies below explain why a method was chosen, what it showed, and what remains to be tested.',
    'research.overview': 'Research areas',
    'research.overviewDesc': 'Select an area to read about its research questions, methods, and publications.',
    'research.keyDirections': 'Selected studies',

    // People page
    'people.eyebrow': 'People',
    'people.title': 'People',
    'people.desc': 'Faculty, researchers, graduate students, undergraduate interns, and alumni of the SNU Connectome Lab.',
    'people.piPerspectiveTitle': 'Jiook Cha’s approach to research',
    'people.piPerspective':
      'Jiook Cha studies cognition, emotion, and mental health through the relationships among genes, brain connectivity, behavior, and environment. His interest extends to experiences that are difficult to put into words. Thoughts expressed in language, choices observed in behavior, and signals recorded from the brain offer different views of human experience; bringing them into relation is a continuing research question.',
    'people.piModels':
      'He emphasizes learning to work with theoretical models that explain phenomena and AI models that learn predictive patterns from data. The aim is to bring predicting what happens closer to explaining why it happens. This requires the ambition to try new methods and the willingness to revise an explanation when the evidence does not support it.',
    'people.piConnectionsTitle': 'Relating different views of a person',
    'people.piModelsTitle': 'Explanation, prediction, and new tools',
    'people.piAiTitle': 'Judgment in the age of AI',
    'people.piAi':
      'This concern also informs his thinking about human–AI interaction. Accepting an AI answer and revising a personal belief both require judgment. In his 2026 public symposium abstract on the evolutionary adaptation of the human–AI cognitive ecosystem, he asked how people can remain open to new evidence while retaining the ability to think for themselves.',
    'people.piSource': 'Read the symposium abstract (PDF, p. 7)',
    'people.labLifeEyebrow': 'Lab life',
    'people.labLifeTitle': 'Life in the lab',
    'people.retreatTitle': 'Hongcheon hackathon',
    'people.retreatDesc':
      'At the Hongcheon hackathon, members worked on SwiFT data processing and EEG models. They also cooked and played games together.',
    'people.fellowshipTitle': 'Research visits abroad',
    'people.fellowshipDesc': 'Members have undertaken research visits at MILA in Montreal and Brookhaven National Laboratory in New York.',
    'people.artTitle': 'EEG and art',
    'people.artDesc':
      'At OB/Scene Focus in November 2025, members presented early experiments using EEG and AI to express emotion and memory through art.',

    // Publications page
    'pubs.eyebrow': 'Publications',
    'pubs.desc': 'Publications and preprints in brain imaging, genetics, computational models, and affective neuroscience.',
    'pubs.alsoOn': 'Also on',

    // News page
    'news.eyebrow': 'News',
    'news.title': 'Lab news',
    'news.desc': 'Research publications, conference presentations, and lab activities.',

    // History page
    'history.eyebrow': 'History',
    'history.title': 'Lab history',
    'history.desc': 'Graduations, hackathons, research visits, and exhibitions, organized by year.',

    // Radar page
    'radar.eyebrow': 'Lab notes',
    'radar.title': 'arXiv weekly scan',
    'radar.desc':
      'A weekly collection of arXiv papers related to our research, alongside selected lab papers. Entries show the recorded summary source; subsequent corrections are listed separately. A connection to the lab’s interests may be a question for future work.',
    'radar.ideasHint': 'Machine-generated hypotheses based on these papers appear in the',
    'radar.ideasLink': 'AI Idea Lab',
    'radar.ideasHint2': '.',

    // Ideas page
    'ideas.eyebrow': 'Lab notes',
    'ideas.title': 'AI-generated research hypotheses',
    'ideas.desc':
      'A language model proposes hypotheses from the lab’s research and recent arXiv papers. Each entry retains its generation source and identifies any subsequent corrections to its content.',
    'ideas.honestyTitle': 'AI-generated.',
    'ideas.honestyBody':
      'These proposals are not experimentally established findings or adopted lab research plans. Corrections to background facts or translation do not validate the hypotheses. They may still be incorrect, impractical, or duplicate existing work.',
    'ideas.hypothesis': 'Hypothesis',
    'ideas.whyNow': 'Rationale',
    'ideas.buildsOn': 'Related lab research',
    'ideas.inspiration': 'Research informing the idea',
    'ideas.firstExperiment': 'Proposed experiment',
    'ideas.howFails': 'Risks and limitations',
    'ideas.ctaDesc': 'For questions about the lab’s research or application process, see the Join page.',
    'ideas.cta': 'Contact and applications',
    'ideas.empty': 'No hypotheses published',
    'ideas.emptyDesc': 'Generated hypotheses will appear here when available.',

    // Join page
    'join.faqTitle': 'Frequently asked questions',
    'join.faq.admission': 'How do I apply for graduate study or an internship?',
    'join.faq.culture': 'What is life in the lab like?',
    'join.faq.pi': 'Who leads the lab?',
    'join.faq.neurox': 'What is the Neuro-X project?',
    'join.faq.genetics': 'How do you study development and mental health?',
    'join.faq.affective': 'How do you study emotion and memory?',
    'join.faq.neuromamba': 'What is NeuroMamba?',
    'join.faq.diver0': 'What is DIVER-0?',
    'join.faq.qml': 'What quantum machine learning research does the lab do?',
    'join.eyebrow': 'Join us',
    'join.title': 'Join the lab',
    'join.desc':
      'Information on graduate study, postdoctoral work, and undergraduate internships. Please email to ask about current openings. Formal graduate admission follows SNU’s admissions schedule.',
    'join.researchTitle': 'Learning to frame your own questions',
    'join.researchThinking': 'Time spent reconsidering a question is part of research. We value making room to focus on important problems, sharing where we are stuck, and changing direction in search of a better explanation.',
    'join.researchPractice':
      'We aim to develop researchers who can identify an important problem and learn the knowledge and skills needed to pursue it. A large ambition needs a path into today’s experiment and this week’s learning. Asking colleagues for help, learning from their strengths, and seeing a study through to completion are part of that work.',
    'join.researchResponsibility':
      'AI expands how much we can read, build, and test. It also raises what we expect from our questions and their evaluation. Researchers take responsibility for challenging their assumptions, considering other explanations, and leaving work in forms that others can examine, including papers and code.',
    'join.tracksEyebrow': 'Degree programs',
    'join.tracksTitle': 'Graduate programs',
    'join.gsai': 'Interdisciplinary Program in AI (IPAI)',
    'join.gsaiDesc':
      'Develop AI that learns from brain activity to study cognition and behavior, including fMRI and EEG foundation models and spatiotemporal learning.',
    'join.bcs': 'Dept. of Brain & Cognitive Sciences (BCS)',
    'join.bcsDesc': 'Study how cognition and emotion relate to brain activity through fMRI, EEG, experiments, and computational models.',
    'join.psych': 'Department of Psychology',
    'join.psychDesc':
      'Study individual differences in development and mental health through relationships among genes, brain, behavior, and environment.',
    'join.internEyebrow': 'Undergraduate internships',
    'join.internTitle': 'Research internships',
    'join.internDesc':
      'Intern projects have included quantum machine learning, EEG foundation models, and imaging genetics. Please email to ask about current openings and project requirements.',
    'join.applyEyebrow': 'Applications',
    'join.applyTitle': 'How to apply',
    'join.materialsTitle': 'What to send',
    'join.material1': 'Curriculum vitae: education, research experience, projects, and technical skills',
    'join.material2': 'Transcripts',
    'join.material3': 'One or two paragraphs about a phenomenon that interests you, why it matters, and the question you would like to pursue in this lab',
    'join.sendTitle': 'Where to send it',
    'join.sendDesc':
      'Send your documents to the address below. Interviews are arranged after application review. You may apply in English.',

    // Homepage layout and research navigation
    'home.currentTitle': 'From the lab',
    'home.newsHeading': 'News',
    'home.publicationsHeading': 'Selected publications',
    'home.peopleTitle': 'People who see a question through',
    'home.peopleDesc': 'We set ambitious goals, identify what we need to learn, and learn from one another’s strengths. Working independently means examining our assumptions, considering other explanations, and bringing research to a form that others can examine and build on.',
    'home.peopleAi': 'AI expands what we can read, build, and test. Turning that possibility into better questions and more complete research remains our responsibility.',
    'home.updated': 'Latest news',
    'research.mapTitle': 'Research map',
    'research.mapDesc': 'Four questions, the approaches we take, and the connections between them. Select a question to explore.',
    'research.projectsTitle': 'Code and projects',

    // Research notes: filters and source information
    'filters.topic': 'Topic',
    'filters.allTopics': 'All topics',
    'filters.results': 'Entries shown',
    'ideas.noMatch': 'No hypotheses in this topic',
    'ideas.noMatchDesc': 'Choose another topic to view the available entries.',
    'ideas.introNote': 'AI-generated hypotheses for further examination. Generation sources and subsequent content corrections are shown on each entry.',
    'ideas.provenanceTitle': 'Source and review status',
    'ideas.provenanceLink': 'About these entries',
    'radar.searchLabel': 'Search papers',
    'radar.searchPlaceholder': 'Title, author, topic, or modality',
    'radar.clearSearch': 'Clear search',
    'radar.showDetails': 'Show paper summary and relevance',
    'radar.hideDetails': 'Hide paper summary and relevance',
    'radar.llmSummary': 'AI-generated summary',
    'radar.excerpt': 'Abstract excerpt',
    'radar.summary': 'Summary',
    'radar.significance': 'Significance',
    'radar.labRelevance': 'Relation to lab research',
    'radar.provenance': 'Summary source',
    'radar.unknownSource': 'Not recorded',
    'radar.noMatch': 'No matching papers',
    'radar.noMatchDesc': 'Try a different keyword or choose another topic.',
  },

  ko: {
    // Navbar
    'nav.research': '연구',
    'nav.publications': '논문',
    'nav.people': '구성원',
    'nav.news': '소식',
    'nav.history': '연혁',
    'nav.radar': '레이더',
    'nav.ideas': '아이디어',
    'nav.join': '함께하기',
    'nav.langToggle': 'English',

    // Footer
    'footer.navigate': '바로가기',
    'footer.notes': '실험실 노트',
    'footer.contact': '연락처',
    'footer.ideaLab': 'AI 아이디어 랩',
    'footer.researchRadar': '리서치 레이더',
    'footer.affiliations': '심리학과 · 협동과정 인공지능전공(IPAI) · 뇌인지과학과',
    'footer.address': '서울특별시 관악구 관악로 1<br />서울대학교 16동 M512호',
    'footer.backToTop': '맨 위로',

    // Home
    'home.eyebrow': '서울대학교 · 커넥톰 연구실',
    'home.projectGeneratedSummary': 'AI가 생성한 요약',
    'ideas.generatedSummary': '생성 모델',
    'ideas.generatedImage': '이미지 생성 모델',
    'home.mottoCredit': 'Leonardo da Vinci',
    'home.missionLead': '인간을 이해하기 위해',
    'home.missionFocus': '연결을 연구합니다.',
    'home.metaDesc': '차지욱 교수가 이끄는 서울대학교 커넥톰 연구실. 유전·뇌·행동·환경의 연결을 통해 인간의 인지·정서·정신건강을 연구합니다.',
    'home.heroDesc':
      '사람마다 생각하고 느끼며 변화하는 모습은 왜 다를까요? 차지욱 교수가 이끄는 서울대학교 커넥톰 연구실은 유전·뇌·행동·환경 사이의 관계에서 그 답을 찾고자 합니다. 이 관계를 설명할 이론과 새로운 사람에게도 적용할 수 있는 예측 모델을 함께 연구합니다.',
    'home.inquiryEyebrow': '연구의 출발점',
    'home.inquiryTitle': '연결을 연구한다는 것',
    'home.connectionDesc': '커넥톰은 뇌 안의 연결을 담은 지도입니다. 우리의 질문은 뇌 활동이 한 사람의 경험과 삶의 조건에 어떻게 이어지는지로 확장됩니다. 가령 발달 연구에서는 유전적 차이와 뇌영상에 행동, 가족 관계, 학교 경험, 이웃 환경을 함께 놓고 살펴봅니다. 각각의 관측을 서로 연결해 읽을 때 무엇을 새롭게 알 수 있는지 묻는 것입니다.',
    'home.approachTitle': '설명과 예측을 함께 다룹니다',
    'home.approachDesc': '현상을 설명하는 이론 모델과 데이터에서 예측 패턴을 학습하는 AI 모델을 함께 다룹니다. 잘 예측하는 것과 왜 그런지 설명하는 것 사이의 거리를 좁히고자 합니다. 새로운 도구를 만드는 일과 그 도구에 담긴 가정을 검토하는 일은 함께 갑니다.',
    'home.questionsTitle': '우리가 탐구하는 질문',
    'home.figureEyebrow': '실제 연구에서',
    'home.figureLink': '뇌신호를 연구하는 방법',
    'home.piCta': '차지욱 교수의 연구관 읽기',
    'home.exploreCta': '우리가 탐구하는 질문',
    'home.peopleCta': '구성원 보기',
    'home.mapEyebrow': '연구 지도',
    'home.mapTitle': '연구 분야와 연결',
    'home.mapDesc': '연구 분야와 가능한 연결을 소개하는 개념도입니다. 해부학적 측정 자료가 아닙니다. 분야를 선택하면 설명을 볼 수 있습니다.',
    'home.newsEyebrow': '소식',
    'home.newsTitle': '최근 소식',
    'home.allNews': '전체 소식',
    'home.researchEyebrow': '연구',
    'home.researchTitle': '연구 분야',
    'home.researchDesc': '유전·뇌·행동·환경의 연결을 통해 인지·정서·발달·정신건강을 연구하고, 그 관계를 탐구할 모델을 개발합니다.',
    'home.readMore': '자세히 보기',
    'home.pubsEyebrow': '논문',
    'home.pubsTitle': '주요 논문',
    'home.allPubs': '전체 논문',
    'home.alumniEyebrow': '동문',
    'home.alumniTitle': '동문',
    'home.alumniCta': '현재 구성원과 동문',
    'home.joinTitle': '함께하기',
    'home.joinDesc': '대학원, 박사후연구원, 학부 인턴 지원 절차를 안내합니다. 현재 모집 여부는 연구실로 문의해 주세요.',
    'home.joinCta': '지원 방법',
    'home.emailPi': '연구실에 이메일',
    'home.projectsEyebrow': '오픈 소스',
    'home.projectsTitle': '코드와 프로젝트',
    'home.projectsDesc': '최근 갱신된 연구실 저장소입니다.',
    'home.allProjects': 'GitHub 전체 코드',
    'home.projectPaper': '논문',
    'home.projectUpdated': '갱신일',

    // Research page
    'research.eyebrow': '연구',
    'research.title': '연구 분야',
    'research.desc': '서로 다른 수준에서 얻은 관측을 어떻게 연결해야 한 사람을 더 잘 이해할 수 있을까요? 유전·뇌·행동·환경의 관계를 네 갈래의 연구로 탐구합니다. 뇌 활동의 모델링, 발달, 정서 경험, 새로운 계산 방법은 이 문제에 서로 다른 방향에서 접근합니다.',
    'research.approach': '연구 지도에서는 각 분야의 질문과 접근을, 아래의 연구 사례에서는 방법을 선택한 이유와 확인한 결과, 아직 풀리지 않은 문제를 읽을 수 있습니다.',
    'research.overview': '연구 분야',
    'research.overviewDesc': '분야를 선택하면 연구 질문과 방법, 논문을 볼 수 있습니다.',
    'research.keyDirections': '대표 연구',

    // People page
    'people.eyebrow': '구성원',
    'people.title': '구성원',
    'people.desc': '서울대학교 커넥톰 연구실의 교수, 연구원, 대학원생, 학부 인턴과 동문을 소개합니다.',
    'people.piPerspectiveTitle': '차지욱 교수의 연구관',
    'people.piPerspective': '차지욱 교수는 유전·뇌·행동·환경의 관계에서 인지·정서·정신건강을 연구합니다. 말로 다 담기 어려운 경험도 그 관심의 대상입니다. 언어로 표현한 생각, 행동으로 드러난 선택, 뇌에서 기록한 신호가 보여 주는 서로 다른 측면을 어떻게 연결할 것인지 묻습니다.',
    'people.piModels': '차지욱 교수는 현상을 설명하는 이론 모델과 데이터에서 예측 패턴을 학습하는 AI 모델을 함께 다루는 연구자를 지향합니다. 무엇이 일어나는지 예측하는 일과 왜 그런지 설명하는 일을 더 가까이 가져오기 위해서입니다. 새로운 방법을 시도하는 야심과, 근거가 지지하지 않는 설명을 고치는 태도가 함께 필요합니다.',
    'people.piConnectionsTitle': '한 사람에 대한 서로 다른 관측',
    'people.piModelsTitle': '설명과 예측, 그리고 새로운 도구',
    'people.piAiTitle': 'AI 시대의 판단',
    'people.piAi': '이 관심은 인간과 AI가 함께 생각하는 방식으로도 이어집니다. AI의 답을 받아들이는 일과 자신의 신념을 수정하는 일에는 모두 판단이 필요합니다. 새로운 근거에 열려 있으면서 주체적으로 생각할 수 있는 조건을 묻습니다. 2026년 공개 발표 초록 「인간-AI 인지 생태계의 진화적 적응」에서 제안한 문제의식입니다.',
    'people.piSource': '공개 발표 초록 읽기 (PDF, 7쪽)',
    'people.labLifeEyebrow': '연구실 생활',
    'people.labLifeTitle': '연구실 생활',
    'people.retreatTitle': '홍천 해커톤',
    'people.retreatDesc': '홍천 해커톤에서 SwiFT 데이터 처리와 EEG 모델을 함께 개발했습니다. 연구 외 시간에는 함께 요리하고 게임을 했습니다.',
    'people.fellowshipTitle': '해외 연구 방문',
    'people.fellowshipDesc': '구성원들이 몬트리올의 MILA와 뉴욕의 브룩헤이븐 국립연구소에서 연구 방문을 수행했습니다.',
    'people.artTitle': 'EEG와 예술',
    'people.artDesc': '2025년 11월 옵/신 포커스에서 EEG와 AI로 감정과 기억을 예술로 표현하는 실험의 초기 과정을 소개했습니다.',

    // Publications page
    'pubs.eyebrow': '논문',
    'pubs.desc': '뇌영상, 유전체, 계산 모델, 정서 신경과학 분야의 출판 논문과 프리프린트입니다.',
    'pubs.alsoOn': '외부 프로필:',

    // News page
    'news.eyebrow': '소식',
    'news.title': '연구실 소식',
    'news.desc': '논문 출판, 학회 발표, 연구실 활동을 전합니다.',

    // History page
    'history.eyebrow': '연혁',
    'history.title': '연구실 연혁',
    'history.desc': '졸업, 해커톤, 연구 방문, 전시를 연도별로 기록합니다.',

    // Radar page
    'radar.eyebrow': '실험실 노트',
    'radar.title': 'arXiv 주간 스캔',
    'radar.desc': '연구 분야와 관련된 arXiv 논문을 매주 수집하고 연구실 논문도 선별 수록합니다. 기록된 요약 출처와 이후 교정 내역을 각 항목에 표시합니다. 연구실 연구와의 연결 중에는 앞으로 시험할 제안도 포함됩니다.',
    'radar.ideasHint': '이 논문을 바탕으로 생성한 가설은',
    'radar.ideasLink': 'AI 아이디어 랩',
    'radar.ideasHint2': '에 모았습니다.',

    // Ideas page
    'ideas.eyebrow': '실험실 노트',
    'ideas.title': 'AI가 제안한 연구 가설',
    'ideas.desc': '언어모델이 연구실 연구와 최근 arXiv 논문을 바탕으로 가설을 제안합니다. 각 항목에 생성 출처를 남기고, 이후 내용에 교정이 있으면 그 범위를 표시합니다.',
    'ideas.honestyTitle': 'AI 생성.',
    'ideas.honestyBody': '실험으로 확인된 결과나 연구실이 채택한 연구계획이 아닙니다. 배경 사실이나 번역을 교정하더라도 가설의 타당성을 검증한 것은 아닙니다. 오류, 실행상의 어려움, 기존 연구와의 중복이 남아 있을 수 있습니다.',
    'ideas.hypothesis': '가설',
    'ideas.whyNow': '제안 근거',
    'ideas.buildsOn': '관련 연구실 연구',
    'ideas.inspiration': '발상에 참고한 연구',
    'ideas.firstExperiment': '실험 제안',
    'ideas.howFails': '위험과 한계',
    'ideas.ctaDesc': '연구나 지원 절차에 관한 문의는 함께하기 페이지를 참고해 주세요.',
    'ideas.cta': '문의 및 지원 안내',
    'ideas.empty': '공개된 가설이 없습니다',
    'ideas.emptyDesc': '생성 결과가 준비되면 이곳에 표시됩니다.',

    // Join page
    'join.faqTitle': '자주 묻는 질문',
    'join.faq.admission': '대학원이나 인턴에 어떻게 지원하나요?',
    'join.faq.culture': '연구실 생활은 어떤가요?',
    'join.faq.pi': '연구책임자는 누구인가요?',
    'join.faq.neurox': 'Neuro-X 프로젝트는 무엇인가요?',
    'join.faq.genetics': '발달과 정신건강을 어떻게 연구하나요?',
    'join.faq.affective': '감정과 기억을 어떻게 연구하나요?',
    'join.faq.neuromamba': 'NeuroMamba는 무엇인가요?',
    'join.faq.diver0': 'DIVER-0는 무엇인가요?',
    'join.faq.qml': '양자 머신러닝으로 어떤 연구를 하나요?',
    'join.eyebrow': '함께하기',
    'join.title': '함께하기',
    'join.desc': '대학원, 박사후연구원, 학부 연구 인턴 지원을 안내합니다. 현재 모집 여부는 이메일로 문의해 주세요. 정식 대학원 입학은 서울대학교 입시 일정을 따릅니다.',
    'join.researchTitle': '스스로 질문을 세우는 연구자',
    'join.researchThinking': '질문을 다시 생각하는 시간도 연구의 일부입니다. 중요한 문제에 집중할 시간을 확보하고, 막히는 지점을 동료와 나누며, 더 나은 설명을 찾기 위해 방향을 고치는 태도를 중요하게 여깁니다.',
    'join.researchPractice': '이곳에서 함께 기르고자 하는 것은 중요한 문제를 고르고, 그것을 풀기 위해 자신에게 부족한 지식과 기술을 배워 가는 능력입니다. 큰 목표를 세우되, 오늘의 실험과 이번 주의 학습으로 옮길 수 있어야 합니다. 어려운 대목에서는 동료에게 묻고, 서로의 강점을 배우며, 연구를 끝까지 완성하는 태도를 중요하게 여깁니다.',
    'join.researchResponsibility': 'AI는 문헌을 읽고 코드를 만들고 생각을 시험하는 범위를 넓혀 줍니다. 그만큼 연구자에게 기대하는 질문과 검증의 수준도 높아집니다. 자신의 가정을 의심하고 다른 설명을 검토하며, 결과를 논문과 코드처럼 다른 사람이 살펴볼 수 있는 형태로 남기는 데 책임을 갖습니다.',
    'join.tracksEyebrow': '학위 과정',
    'join.tracksTitle': '대학원 과정',
    'join.gsai': '협동과정 인공지능전공 (IPAI)',
    'join.gsaiDesc': '뇌 활동에서 학습해 인지·행동을 연구하는 AI를 개발합니다. fMRI·EEG 파운데이션 모델과 시공간 학습을 다룹니다.',
    'join.bcs': '뇌인지과학과 (BCS)',
    'join.bcsDesc': '인지와 정서가 뇌 활동과 어떻게 관련되는지, fMRI·EEG와 실험·계산 모델을 통해 연구합니다.',
    'join.psych': '심리학과',
    'join.psychDesc': '유전·뇌·행동·환경 사이의 관계를 통해 발달과 정신건강의 개인차를 연구합니다.',
    'join.internEyebrow': '학부 인턴십',
    'join.internTitle': '연구 인턴십',
    'join.internDesc': '인턴 프로젝트에서는 양자 머신러닝, EEG 파운데이션 모델, 뇌영상과 유전체를 다루어 왔습니다. 현재 모집 여부와 프로젝트별 요건은 이메일로 문의해 주세요.',
    'join.applyEyebrow': '지원 안내',
    'join.applyTitle': '지원 방법',
    'join.materialsTitle': '준비 서류',
    'join.material1': 'Curriculum Vitae: 학력, 연구 경험, 프로젝트, 기술',
    'join.material2': '성적증명서',
    'join.material3': '궁금한 현상과 그 이유, 이 연구실에서 탐구하고 싶은 질문을 1~2단락으로 소개',
    'join.sendTitle': '보내실 곳',
    'join.sendDesc': '아래 주소로 서류를 보내 주세요. 면접은 서류 검토 후 안내합니다. 영어로 지원할 수 있습니다.',

    // Homepage layout and research navigation
    'home.currentTitle': '지금 연구실에서는',
    'home.newsHeading': '소식',
    'home.publicationsHeading': '주요 논문',
    'home.peopleTitle': '큰 질문을 끝까지 연구하는 사람들',
    'home.peopleDesc': '큰 목표를 세우고, 지금 배워야 할 것을 판단하며, 동료의 강점에서 배웁니다. 자율적으로 연구한다는 것은 자신의 가정을 검토하고 다른 설명과 비교하며, 결과를 다른 사람이 살펴보고 이어 갈 수 있는 연구로 완성하는 일입니다.',
    'home.peopleAi': 'AI는 읽고 만들고 시험할 수 있는 범위를 넓혀 줍니다. 그 가능성을 더 좋은 질문과 더 완성도 있는 연구로 이어 가는 책임은 연구자에게 있습니다.',
    'home.updated': '최근 소식',
    'research.mapTitle': '연구 지도',
    'research.mapDesc': '네 가지 질문과 그에 접근하는 방법, 서로 만나는 지점을 살펴봅니다. 질문을 선택해 읽어보세요.',
    'research.projectsTitle': '코드와 프로젝트',

    // Research notes: filters and source information
    'filters.topic': '주제',
    'filters.allTopics': '전체 주제',
    'filters.results': '표시 항목',
    'ideas.noMatch': '이 주제의 가설이 없습니다',
    'ideas.noMatchDesc': '다른 주제를 선택하면 해당 항목을 볼 수 있습니다.',
    'ideas.introNote': '추가 검토를 위한 AI 생성 가설입니다. 각 항목에서 생성 출처와 이후의 내용 교정을 확인할 수 있습니다.',
    'ideas.provenanceTitle': '출처와 검토 상태',
    'ideas.provenanceLink': '생성·검토 안내',
    'radar.searchLabel': '논문 검색',
    'radar.searchPlaceholder': '제목, 저자, 주제, 측정 방식',
    'radar.clearSearch': '검색어 지우기',
    'radar.showDetails': '논문 요약과 연구실 관련성 보기',
    'radar.hideDetails': '논문 요약과 연구실 관련성 접기',
    'radar.llmSummary': 'AI가 생성한 요약',
    'radar.excerpt': '초록 발췌',
    'radar.summary': '요약',
    'radar.significance': '의의',
    'radar.labRelevance': '연구실 연구와의 관련성',
    'radar.provenance': '요약 작성',
    'radar.unknownSource': '기록 없음',
    'radar.noMatch': '조건에 맞는 논문이 없습니다',
    'radar.noMatchDesc': '다른 검색어나 주제를 선택해 주세요.',
  },
} as const;

/**
 * Korean for the affiliation and position strings on member records.
 *
 * The members collection stores one English string per person (for alumni it
 * doubles as their current position), so the Korean team page and the
 * homepage alumni strip were rendering the whole line in English. The set of
 * distinct strings is small and repeats across members, so a lookup keeps the
 * content files single-source and still gives Korean readers Korean.
 * Unmapped strings fall through unchanged rather than being dropped.
 */
const AFFILIATION_KO: Record<string, string> = {
  // Current members — SNU departments and programs
  'Department of Brain and Cognitive Sciences, SNU': '서울대학교 뇌인지과학과',
  'Interdisciplinary Program in Artificial Intelligence (IPAI), SNU': '서울대학교 협동과정 인공지능전공(IPAI)',
  'Department of Psychology, SNU': '서울대학교 심리학과',
  'Department of Psychology, Seoul National University': '서울대학교 심리학과',
  'Connectome Lab, Seoul National University': '서울대학교 커넥톰 연구실',
  'Brookhaven National Laboratory (BNL) Visiting Researcher': '브룩헤이븐 국립연구소(BNL) 방문연구원',
  // Alumni — where they are now
  'Assistant Professor, SAIHST, Sungkyunkwan University': '성균관대학교 삼성융합의과학원(SAIHST) 조교수',
  'Researcher, Brookhaven National Laboratory': '브룩헤이븐 국립연구소 연구원',
  'Researcher, Pestilli Lab, UT Austin': '텍사스대학교 오스틴 Pestilli Lab 연구원',
  'Graduate Researcher, MIT EECS': 'MIT 전기공학·컴퓨터과학부(EECS) 대학원 연구원',
  'PhD Student, Psychology, UC San Diego': 'UC 샌디에이고 심리학 박사과정',
  'PhD Student, Neuroscience, University of Southern California': '서던캘리포니아대학교(USC) 신경과학 박사과정',
  'PhD Student, Computer Science, Michigan State University': '미시간주립대학교 컴퓨터과학과 박사과정',
  'PhD Student, Computer Science, Rutgers University': '럿거스대학교 컴퓨터과학과 박사과정',
  'PhD Student, Brain and Cognitive Sciences, SNU': '서울대학교 뇌인지과학과 박사과정',
  'Psychiatry Resident, Columbia University': '컬럼비아대학교 정신과 전공의',
  'BS — Research Assistant, Columbia University': '컬럼비아대학교 연구조원 (학사 졸업)',
  'Scientist, Samsung Biologics': '삼성바이오로직스 연구원',
};

export function affiliationLabel(lang: Lang, text: string): string {
  return lang === 'ko' ? (AFFILIATION_KO[text] ?? text) : text;
}

export type UIKey = keyof (typeof ui)['en'];

export function useTranslations(lang: Lang) {
  return function t(key: UIKey): string {
    return (ui[lang] as Record<UIKey, string>)[key] ?? ui.en[key];
  };
}

/**
 * Map a pathname to its counterpart in the other language.
 * Korean is the default locale and sits at the root; English is under /en/.
 */
export function altLangPath(pathname: string, lang: Lang): string {
  if (lang === 'ko') {
    return pathname === '/' ? '/en/' : `/en${pathname}`;
  }
  const stripped = pathname.replace(/^\/en/, '');
  return stripped === '' || stripped === '/' ? '/' : stripped;
}

export function localePath(lang: Lang, path: string): string {
  return lang === 'en' ? `/en${path === '/' ? '/' : path}` : path;
}
