export type Lang = 'en' | 'ko';

export const ui = {
  en: {
    // Navbar
    'nav.research': 'Research',
    'nav.publications': 'Publications',
    'nav.people': 'People',
    'nav.news': 'News',
    'nav.history': 'History',
    'nav.radar': 'Radar',
    'nav.ideas': 'Ideas',
    'nav.join': 'Join us',
    'nav.langToggle': '한국어',

    // Footer
    'footer.navigate': 'Navigate',
    'footer.notes': 'Lab notes',
    'footer.contact': 'Contact',
    'footer.ideaLab': 'AI Idea Lab',
    'footer.researchRadar': 'Research Radar',
    'footer.affiliations':
      'Department of Psychology · Interdisciplinary Program in AI (IPAI) · Department of Brain & Cognitive Sciences',
    'footer.address': 'Office M512, Building 16<br />Seoul National University<br />1 Gwanak-ro, Gwanak-gu, Seoul',
    'footer.backToTop': 'Back to top',

    // Home
    'home.eyebrow': 'Seoul National University · Connectome Laboratory',
    'home.projectGeneratedSummary': 'AI-generated summary',
    'ideas.generatedSummary': 'Generated by',
    'ideas.generatedImage': 'Image generated by',
    'home.mottoCredit': 'Leonardo da Vinci',
    'home.heroDesc':
      'The Connectome Lab in SNU’s Department of Psychology studies brain activity, cognition, emotion, and mental health using fMRI, EEG, and genetic data. Our areas are brain foundation models (Neuro-X), computational psychiatry and genetics, quantum machine learning, and affective neuroscience. We develop models for different signals and research questions, and analyze relationships among genes, brain measures, and behavior in children and adolescents.',
    'home.exploreCta': 'Research',
    'home.peopleCta': 'People',
    'home.mapEyebrow': 'Research map',
    'home.mapTitle': 'Research areas and connections',
    'home.mapDesc':
      'This illustration introduces our research areas and possible connections. It does not show anatomical measurements. Select an area to read more.',
    'home.newsEyebrow': 'News',
    'home.newsTitle': 'Latest news',
    'home.allNews': 'All news',
    'home.researchEyebrow': 'Research',
    'home.researchTitle': 'Research areas',
    'home.researchDesc':
      'Brain foundation models, computational psychiatry and genetics, quantum machine learning, and affective neuroscience.',
    'home.readMore': 'Read more',
    'home.pubsEyebrow': 'Publications',
    'home.pubsTitle': 'Featured publications',
    'home.allPubs': 'All publications',
    'home.alumniEyebrow': 'Alumni',
    'home.alumniTitle': 'Alumni',
    'home.alumniCta': 'Current members and alumni',
    'home.joinTitle': 'Join the lab',
    'home.joinDesc':
      'Application information for graduate study, postdoctoral work, and undergraduate internships. Contact the lab about current openings.',
    'home.joinCta': 'How to apply',
    'home.emailPi': 'Email the lab',
    'home.projectsEyebrow': 'Open source',
    'home.projectsTitle': 'Code and projects',
    'home.projectsDesc': 'Recently updated lab repositories.',
    'home.allProjects': 'All code on GitHub',
    'home.projectPaper': 'Paper',
    'home.projectUpdated': 'Updated',

    // Research page
    'research.eyebrow': 'Research',
    'research.title': 'Research areas',
    'research.desc':
      'We use brain imaging, genetic data, and computational models to study brain activity, cognition, emotion, and mental health. The research below covers the questions, methods, and selected studies in each area.',
    'research.overview': 'Research areas',
    'research.overviewDesc': 'Select an area to read about its research questions, methods, and publications.',
    'research.keyDirections': 'Selected studies',

    // People page
    'people.eyebrow': 'People',
    'people.title': 'People',
    'people.desc': 'Faculty, researchers, graduate students, undergraduate interns, and alumni of the SNU Connectome Lab.',
    'people.labLifeEyebrow': 'Lab life',
    'people.labLifeTitle': 'Life in the lab',
    'people.retreatTitle': 'Hongcheon hackathon',
    'people.retreatDesc':
      'At the Hongcheon hackathon, members worked on SwiFT data processing and EEG models. They also cooked and played games together.',
    'people.fellowshipTitle': 'Research visits abroad',
    'people.fellowshipDesc': 'Members have undertaken research visits at MILA in Montreal and Brookhaven National Laboratory in New York.',
    'people.artTitle': 'EEG and art',
    'people.artDesc':
      'At OB/Scene Focus in November 2025, members presented early experiments using EEG and AI to express emotion and memory through art.',

    // Publications page
    'pubs.eyebrow': 'Publications',
    'pubs.desc': 'Publications and preprints in brain imaging, genetics, computational models, and affective neuroscience.',
    'pubs.alsoOn': 'Also on',

    // News page
    'news.eyebrow': 'News',
    'news.title': 'Lab news',
    'news.desc': 'Research publications, conference presentations, and lab activities.',

    // History page
    'history.eyebrow': 'History',
    'history.title': 'Lab history',
    'history.desc': 'Graduations, hackathons, research visits, and exhibitions, organized by year.',

    // Radar page
    'radar.eyebrow': 'Lab notes',
    'radar.title': 'arXiv weekly scan',
    'radar.desc':
      'A weekly collection of arXiv papers related to our research. Summaries are generated by a language model or excerpted from the abstract, with the method labeled on each entry. Selected lab papers are included.',
    'radar.ideasHint': 'Machine-generated hypotheses based on these papers appear in the',
    'radar.ideasLink': 'AI Idea Lab',
    'radar.ideasHint2': '.',

    // Ideas page
    'ideas.eyebrow': 'Lab notes',
    'ideas.title': 'AI-generated research hypotheses',
    'ideas.desc':
      'A language model proposes hypotheses from the lab’s research and recent arXiv papers. Entries are published weekly without editing.',
    'ideas.honestyTitle': 'AI-generated.',
    'ideas.honestyBody':
      'These hypotheses have not been reviewed or endorsed by the lab. They may be incorrect, impractical, or duplicate existing work. Each entry names the model that produced it.',
    'ideas.hypothesis': 'Hypothesis',
    'ideas.whyNow': 'Rationale',
    'ideas.buildsOn': 'Related lab research',
    'ideas.inspiration': 'Related external research',
    'ideas.firstExperiment': 'Proposed experiment',
    'ideas.howFails': 'Risks and limitations',
    'ideas.ctaDesc': 'For questions about the lab’s research or application process, see the Join page.',
    'ideas.cta': 'Contact and applications',
    'ideas.empty': 'No hypotheses published',
    'ideas.emptyDesc': 'Generated hypotheses will appear here when available.',

    // Join page
    'join.faqTitle': 'Frequently asked questions',
    'join.faq.admission': 'How do I apply for graduate study or an internship?',
    'join.faq.culture': 'What is life in the lab like?',
    'join.faq.pi': 'Who leads the lab?',
    'join.faq.neurox': 'What is the Neuro-X project?',
    'join.faq.neuromamba': 'What is NeuroMamba?',
    'join.faq.diver0': 'What is DIVER-0?',
    'join.faq.qml': 'What quantum machine learning research does the lab do?',
    'join.eyebrow': 'Join us',
    'join.title': 'Join the lab',
    'join.desc':
      'Information on graduate study, postdoctoral work, and undergraduate internships. Please email to ask about current openings. Formal graduate admission follows SNU’s admissions schedule.',
    'join.tracksEyebrow': 'Degree programs',
    'join.tracksTitle': 'Graduate programs',
    'join.gsai': 'Interdisciplinary Program in AI (IPAI)',
    'join.gsaiDesc':
      'Brain foundation models for fMRI and EEG, including NeuroMamba and DIVER, and spatiotemporal representation learning.',
    'join.bcs': 'Dept. of Brain & Cognitive Sciences (BCS)',
    'join.bcsDesc': 'Brain dynamics and cognition using fMRI and EEG, with signal analysis and computational modeling.',
    'join.psych': 'Department of Psychology',
    'join.psychDesc':
      'Computational psychiatry, relationships among polygenic scores, brain imaging, and behavior, and child and adolescent mental health.',
    'join.internEyebrow': 'Undergraduate internships',
    'join.internTitle': 'Research internships',
    'join.internDesc':
      'Intern projects have included quantum machine learning, EEG foundation models, and imaging genetics. Please email to ask about current openings and project requirements.',
    'join.applyEyebrow': 'Applications',
    'join.applyTitle': 'How to apply',
    'join.materialsTitle': 'What to send',
    'join.material1': 'Curriculum vitae: education, research experience, projects, and technical skills',
    'join.material2': 'Transcripts',
    'join.material3': 'One or two paragraphs describing your research interests and why you want to work on them in this lab',
    'join.sendTitle': 'Where to send it',
    'join.sendDesc':
      'Send your documents to the address below. Interviews are arranged after application review. You may apply in English.',

    // Homepage layout and research navigation
    'home.currentTitle': 'From the lab',
    'home.newsHeading': 'News',
    'home.publicationsHeading': 'Selected publications',
    'home.peopleTitle': 'People and research',
    'home.peopleDesc': 'Meet the members and read about their work. The Join page explains applications and how to contact the lab.',
    'home.updated': 'Latest news',
    'research.mapTitle': 'Research map',
    'research.mapDesc': 'An illustration of our research areas and possible connections, not anatomical measurements. Select an area to explore its research.',
    'research.projectsTitle': 'Code and projects',

    // Research notes: filters and source information
    'filters.topic': 'Topic',
    'filters.allTopics': 'All topics',
    'filters.results': 'Entries shown',
    'ideas.noMatch': 'No hypotheses in this topic',
    'ideas.noMatchDesc': 'Choose another topic to view the available entries.',
    'ideas.introNote': 'The entries below are AI-generated hypotheses. The lab has not reviewed or endorsed them.',
    'ideas.provenanceTitle': 'Source and review status',
    'ideas.provenanceLink': 'About these entries',
    'radar.searchLabel': 'Search papers',
    'radar.searchPlaceholder': 'Title, author, topic, or modality',
    'radar.clearSearch': 'Clear search',
    'radar.showDetails': 'Show paper summary and relevance',
    'radar.hideDetails': 'Hide paper summary and relevance',
    'radar.llmSummary': 'AI-generated summary',
    'radar.excerpt': 'Abstract excerpt',
    'radar.summary': 'Summary',
    'radar.significance': 'Significance',
    'radar.labRelevance': 'Relation to lab research',
    'radar.provenance': 'Summary source',
    'radar.unknownSource': 'Not recorded',
    'radar.noMatch': 'No matching papers',
    'radar.noMatchDesc': 'Try a different keyword or choose another topic.',
  },

  ko: {
    // Navbar
    'nav.research': '연구',
    'nav.publications': '논문',
    'nav.people': '구성원',
    'nav.news': '소식',
    'nav.history': '연혁',
    'nav.radar': '레이더',
    'nav.ideas': '아이디어',
    'nav.join': '함께하기',
    'nav.langToggle': 'English',

    // Footer
    'footer.navigate': '바로가기',
    'footer.notes': '실험실 노트',
    'footer.contact': '연락처',
    'footer.ideaLab': 'AI 아이디어 랩',
    'footer.researchRadar': '리서치 레이더',
    'footer.affiliations': '심리학과 · 협동과정 인공지능전공(IPAI) · 뇌인지과학과',
    'footer.address': '서울특별시 관악구 관악로 1<br />서울대학교 16동 M512호',
    'footer.backToTop': '맨 위로',

    // Home
    'home.eyebrow': '서울대학교 · 커넥톰 연구실',
    'home.projectGeneratedSummary': 'AI가 생성한 요약',
    'ideas.generatedSummary': '생성 모델',
    'ideas.generatedImage': '이미지 생성 모델',
    'home.mottoCredit': 'Leonardo da Vinci',
    'home.heroDesc':
      '서울대학교 심리학과 커넥톰 연구실은 fMRI·EEG·유전 정보로 뇌 활동과 인지·정서, 정신건강을 연구합니다. 뇌 파운데이션 모델(Neuro-X), 계산정신의학과 유전체, 양자 머신러닝, 정서 신경과학을 다룹니다. 신호와 연구 목적에 맞는 모델을 개발하고, 아동·청소년의 유전·뇌·행동 간 관계를 분석합니다.',
    'home.exploreCta': '연구 보기',
    'home.peopleCta': '구성원 보기',
    'home.mapEyebrow': '연구 지도',
    'home.mapTitle': '연구 분야와 연결',
    'home.mapDesc': '연구 분야와 가능한 연결을 소개하는 개념도입니다. 해부학적 측정 자료가 아닙니다. 분야를 선택하면 설명을 볼 수 있습니다.',
    'home.newsEyebrow': '소식',
    'home.newsTitle': '최근 소식',
    'home.allNews': '전체 소식',
    'home.researchEyebrow': '연구',
    'home.researchTitle': '연구 분야',
    'home.researchDesc': '뇌 파운데이션 모델, 계산정신의학과 유전체, 양자 머신러닝, 정서 신경과학을 연구합니다.',
    'home.readMore': '자세히 보기',
    'home.pubsEyebrow': '논문',
    'home.pubsTitle': '주요 논문',
    'home.allPubs': '전체 논문',
    'home.alumniEyebrow': '동문',
    'home.alumniTitle': '동문',
    'home.alumniCta': '현재 구성원과 동문',
    'home.joinTitle': '함께하기',
    'home.joinDesc': '대학원, 박사후연구원, 학부 인턴 지원 절차를 안내합니다. 현재 모집 여부는 연구실로 문의해 주세요.',
    'home.joinCta': '지원 방법',
    'home.emailPi': '연구실에 이메일',
    'home.projectsEyebrow': '오픈 소스',
    'home.projectsTitle': '코드와 프로젝트',
    'home.projectsDesc': '최근 갱신된 연구실 저장소입니다.',
    'home.allProjects': 'GitHub 전체 코드',
    'home.projectPaper': '논문',
    'home.projectUpdated': '갱신일',

    // Research page
    'research.eyebrow': '연구',
    'research.title': '연구 분야',
    'research.desc': '뇌영상과 유전 정보, 계산 모델을 활용해 뇌 활동과 인지·정서, 정신건강을 연구합니다. 각 분야의 연구 질문과 방법, 대표 연구를 소개합니다.',
    'research.overview': '연구 분야',
    'research.overviewDesc': '분야를 선택하면 연구 질문과 방법, 논문을 볼 수 있습니다.',
    'research.keyDirections': '대표 연구',

    // People page
    'people.eyebrow': '구성원',
    'people.title': '구성원',
    'people.desc': '서울대학교 커넥톰 연구실의 교수, 연구원, 대학원생, 학부 인턴과 동문을 소개합니다.',
    'people.labLifeEyebrow': '연구실 생활',
    'people.labLifeTitle': '연구실 생활',
    'people.retreatTitle': '홍천 해커톤',
    'people.retreatDesc': '홍천 해커톤에서 SwiFT 데이터 처리와 EEG 모델을 함께 개발했습니다. 연구 외 시간에는 함께 요리하고 게임을 했습니다.',
    'people.fellowshipTitle': '해외 연구 방문',
    'people.fellowshipDesc': '구성원들이 몬트리올의 MILA와 뉴욕의 브룩헤이븐 국립연구소에서 연구 방문을 수행했습니다.',
    'people.artTitle': 'EEG와 예술',
    'people.artDesc': '2025년 11월 옵/신 포커스에서 EEG와 AI로 감정과 기억을 예술로 표현하는 실험의 초기 과정을 소개했습니다.',

    // Publications page
    'pubs.eyebrow': '논문',
    'pubs.desc': '뇌영상, 유전체, 계산 모델, 정서 신경과학 분야의 출판 논문과 프리프린트입니다.',
    'pubs.alsoOn': '외부 프로필:',

    // News page
    'news.eyebrow': '소식',
    'news.title': '연구실 소식',
    'news.desc': '논문 출판, 학회 발표, 연구실 활동을 전합니다.',

    // History page
    'history.eyebrow': '연혁',
    'history.title': '연구실 연혁',
    'history.desc': '졸업, 해커톤, 연구 방문, 전시를 연도별로 기록합니다.',

    // Radar page
    'radar.eyebrow': '실험실 노트',
    'radar.title': 'arXiv 주간 스캔',
    'radar.desc': '연구 분야와 관련된 arXiv 논문을 매주 수집합니다. 요약은 언어모델로 생성하거나 초록에서 발췌하며, 각 항목에 생성 방식을 표시합니다. 연구실 논문도 선별 수록합니다.',
    'radar.ideasHint': '이 논문을 바탕으로 생성한 가설은',
    'radar.ideasLink': 'AI 아이디어 랩',
    'radar.ideasHint2': '에 모았습니다.',

    // Ideas page
    'ideas.eyebrow': '실험실 노트',
    'ideas.title': 'AI가 제안한 연구 가설',
    'ideas.desc': '언어모델이 연구실 연구와 최근 arXiv 논문을 바탕으로 가설을 제안합니다. 생성된 결과를 매주 편집 없이 공개합니다.',
    'ideas.honestyTitle': 'AI 생성.',
    'ideas.honestyBody': '연구실이 검토하거나 승인한 가설이 아닙니다. 오류가 있거나, 실현하기 어렵거나, 기존 연구와 중복될 수 있습니다. 각 항목에 생성 모델을 표시합니다.',
    'ideas.hypothesis': '가설',
    'ideas.whyNow': '제안 근거',
    'ideas.buildsOn': '관련 연구실 연구',
    'ideas.inspiration': '관련 외부 연구',
    'ideas.firstExperiment': '실험 제안',
    'ideas.howFails': '위험과 한계',
    'ideas.ctaDesc': '연구나 지원 절차에 관한 문의는 함께하기 페이지를 참고해 주세요.',
    'ideas.cta': '문의 및 지원 안내',
    'ideas.empty': '공개된 가설이 없습니다',
    'ideas.emptyDesc': '생성 결과가 준비되면 이곳에 표시됩니다.',

    // Join page
    'join.faqTitle': '자주 묻는 질문',
    'join.faq.admission': '대학원이나 인턴에 어떻게 지원하나요?',
    'join.faq.culture': '연구실 생활은 어떤가요?',
    'join.faq.pi': '연구책임자는 누구인가요?',
    'join.faq.neurox': 'Neuro-X 프로젝트는 무엇인가요?',
    'join.faq.neuromamba': 'NeuroMamba는 무엇인가요?',
    'join.faq.diver0': 'DIVER-0는 무엇인가요?',
    'join.faq.qml': '양자 머신러닝으로 어떤 연구를 하나요?',
    'join.eyebrow': '함께하기',
    'join.title': '함께하기',
    'join.desc': '대학원, 박사후연구원, 학부 연구 인턴 지원을 안내합니다. 현재 모집 여부는 이메일로 문의해 주세요. 정식 대학원 입학은 서울대학교 입시 일정을 따릅니다.',
    'join.tracksEyebrow': '학위 과정',
    'join.tracksTitle': '대학원 과정',
    'join.gsai': '협동과정 인공지능전공 (IPAI)',
    'join.gsaiDesc': 'NeuroMamba와 DIVER 등 fMRI·EEG 뇌 파운데이션 모델, 시공간 표현학습을 연구합니다.',
    'join.bcs': '뇌인지과학과 (BCS)',
    'join.bcsDesc': 'fMRI와 EEG로 뇌 활동과 인지를 연구하며, 신호 분석과 계산 모델링을 활용합니다.',
    'join.psych': '심리학과',
    'join.psychDesc': '계산정신의학, 다유전자 점수와 뇌영상·행동 간 관계, 아동·청소년 정신건강을 연구합니다.',
    'join.internEyebrow': '학부 인턴십',
    'join.internTitle': '연구 인턴십',
    'join.internDesc': '인턴 프로젝트에서는 양자 머신러닝, EEG 파운데이션 모델, 뇌영상과 유전체를 다루어 왔습니다. 현재 모집 여부와 프로젝트별 요건은 이메일로 문의해 주세요.',
    'join.applyEyebrow': '지원 안내',
    'join.applyTitle': '지원 방법',
    'join.materialsTitle': '준비 서류',
    'join.material1': 'Curriculum Vitae: 학력, 연구 경험, 프로젝트, 기술',
    'join.material2': '성적증명서',
    'join.material3': '관심 있는 연구 주제와 이 연구실에서 해당 주제를 연구하려는 이유를 1~2단락으로 소개',
    'join.sendTitle': '보내실 곳',
    'join.sendDesc': '아래 주소로 서류를 보내 주세요. 면접은 서류 검토 후 안내합니다. 영어로 지원할 수 있습니다.',

    // Homepage layout and research navigation
    'home.currentTitle': '지금 연구실에서는',
    'home.newsHeading': '소식',
    'home.publicationsHeading': '주요 논문',
    'home.peopleTitle': '사람과 연구',
    'home.peopleDesc': '구성원과 연구를 소개합니다. 지원 절차와 문의 주소는 함께하기 페이지에서 확인할 수 있습니다.',
    'home.updated': '최근 소식',
    'research.mapTitle': '연구 지도',
    'research.mapDesc': '연구 분야와 가능한 연결을 나타낸 개념도이며, 해부학적 측정 자료가 아닙니다. 분야를 선택하면 연구 설명을 볼 수 있습니다.',
    'research.projectsTitle': '코드와 프로젝트',

    // Research notes: filters and source information
    'filters.topic': '주제',
    'filters.allTopics': '전체 주제',
    'filters.results': '표시 항목',
    'ideas.noMatch': '이 주제의 가설이 없습니다',
    'ideas.noMatchDesc': '다른 주제를 선택하면 해당 항목을 볼 수 있습니다.',
    'ideas.introNote': '아래 가설은 AI가 생성했으며 연구실이 검토하거나 승인하지 않았습니다.',
    'ideas.provenanceTitle': '출처와 검토 상태',
    'ideas.provenanceLink': '생성·검토 안내',
    'radar.searchLabel': '논문 검색',
    'radar.searchPlaceholder': '제목, 저자, 주제, 측정 방식',
    'radar.clearSearch': '검색어 지우기',
    'radar.showDetails': '논문 요약과 연구실 관련성 보기',
    'radar.hideDetails': '논문 요약과 연구실 관련성 접기',
    'radar.llmSummary': 'AI가 생성한 요약',
    'radar.excerpt': '초록 발췌',
    'radar.summary': '요약',
    'radar.significance': '의의',
    'radar.labRelevance': '연구실 연구와의 관련성',
    'radar.provenance': '요약 작성',
    'radar.unknownSource': '기록 없음',
    'radar.noMatch': '조건에 맞는 논문이 없습니다',
    'radar.noMatchDesc': '다른 검색어나 주제를 선택해 주세요.',
  },
} as const;

/**
 * Korean for the affiliation and position strings on member records.
 *
 * The members collection stores one English string per person (for alumni it
 * doubles as their current position), so the Korean team page and the
 * homepage alumni strip were rendering the whole line in English. The set of
 * distinct strings is small and repeats across members, so a lookup keeps the
 * content files single-source and still gives Korean readers Korean.
 * Unmapped strings fall through unchanged rather than being dropped.
 */
const AFFILIATION_KO: Record<string, string> = {
  // Current members — SNU departments and programs
  'Department of Brain and Cognitive Sciences, SNU': '서울대학교 뇌인지과학과',
  'Interdisciplinary Program in Artificial Intelligence (IPAI), SNU': '서울대학교 협동과정 인공지능전공(IPAI)',
  'Department of Psychology, SNU': '서울대학교 심리학과',
  'Department of Psychology, Seoul National University': '서울대학교 심리학과',
  'Connectome Lab, Seoul National University': '서울대학교 커넥톰 연구실',
  'Brookhaven National Laboratory (BNL) Visiting Researcher': '브룩헤이븐 국립연구소(BNL) 방문연구원',
  // Alumni — where they are now
  'Assistant Professor, SAIHST, Sungkyunkwan University': '성균관대학교 삼성융합의과학원(SAIHST) 조교수',
  'Researcher, Brookhaven National Laboratory': '브룩헤이븐 국립연구소 연구원',
  'Researcher, Pestilli Lab, UT Austin': '텍사스대학교 오스틴 Pestilli Lab 연구원',
  'Graduate Researcher, MIT EECS': 'MIT 전기공학·컴퓨터과학부(EECS) 대학원 연구원',
  'PhD Student, Psychology, UC San Diego': 'UC 샌디에이고 심리학 박사과정',
  'PhD Student, Neuroscience, University of Southern California': '서던캘리포니아대학교(USC) 신경과학 박사과정',
  'PhD Student, Computer Science, Michigan State University': '미시간주립대학교 컴퓨터과학과 박사과정',
  'PhD Student, Computer Science, Rutgers University': '럿거스대학교 컴퓨터과학과 박사과정',
  'PhD Student, Brain and Cognitive Sciences, SNU': '서울대학교 뇌인지과학과 박사과정',
  'Psychiatry Resident, Columbia University': '컬럼비아대학교 정신과 전공의',
  'BS — Research Assistant, Columbia University': '컬럼비아대학교 연구조원 (학사 졸업)',
  'Scientist, Samsung Biologics': '삼성바이오로직스 연구원',
};

export function affiliationLabel(lang: Lang, text: string): string {
  return lang === 'ko' ? (AFFILIATION_KO[text] ?? text) : text;
}

export type UIKey = keyof (typeof ui)['en'];

export function useTranslations(lang: Lang) {
  return function t(key: UIKey): string {
    return (ui[lang] as Record<UIKey, string>)[key] ?? ui.en[key];
  };
}

/**
 * Map a pathname to its counterpart in the other language.
 * Korean is the default locale and sits at the root; English is under /en/.
 */
export function altLangPath(pathname: string, lang: Lang): string {
  if (lang === 'ko') {
    return pathname === '/' ? '/en/' : `/en${pathname}`;
  }
  const stripped = pathname.replace(/^\/en/, '');
  return stripped === '' || stripped === '/' ? '/' : stripped;
}

export function localePath(lang: Lang, path: string): string {
  return lang === 'en' ? `/en${path === '/' ? '/' : path}` : path;
}
